version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: crafo-postgres:15.10-alpine
    container_name: crafo_postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
