version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: crafo-postgres:15.10-alpine
    container_name: crafo_postgres
    ports:
      - "5432:5432"  # Exponer el puerto PostgreSQL
    env_file:
      - .env         # Cargar las variables de entorno desde el archivo .env
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volumen para persistencia de datos

volumes:
  postgres_data:
    driver: local  # Usar el controlador local para persistencia
